[project]
name = "mlframework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.0",
    "kaggle>=1.6.6",
    "matplotlib>=3.8.2",
    "numpy>=1.26.4",
    "pandas>=2.2.0",
    "python-dotenv>=1.0.1",
    "tqdm>=4.66.4",
]

[tool.setuptools]
py-modules = ["mlframework"]

[dependency-groups]
dev = ["pre-commit>=3.6.0"]
