[tool.poetry]
name = "mlframework"
version = "0.1.0"
description = ""
authors = ["kristian ehlert"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
ipykernel = "^6.29.0"
matplotlib = "^3.8.2"
kaggle = "^1.6.6"
numpy = "^1.26.4"
pandas = "^2.2.0"
plotly = "^5.19.0"
albumentations = "^1.4.0"
seqeval = {version = "^1.2.2", optional = true}
evaluate = {version = "^0.4.1", optional = true}
arckit = {path = "../code/arckit", develop = true, optional = true}
tinygrad = {version = "^0.9.1", optional = true}
rigging = {extras = ["all"], version = "^2.0.2", optional = true}
bitsandbytes = {version = "^0.43.2", optional = true}


[tool.poetry.extras]
torch-cuda121 = ["torch", "torchvision", "torchaudio"]
pii = ["seqeval", "evaluate", "accelerate"]
arc = ["arckit"]
grad = ["tinygrad"]
rig = ["rigging", "bitsandbytes"]


[[tool.poetry.source]]
name = "torch-121"
url = "https://download.pytorch.org/whl/cu121"
priority = "supplemental"


[tool.poetry.group.dev.dependencies]
pre-commit = "^3.6.0"


[tool.poetry.group.leash.dependencies]
rdkit = "^2023.9.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
