[project]
name = "kego"
version = "0.5.0"
description = "Helpers for quick ML analysis of kaggle competitions."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "kaggle>=1.6.6",
    "numpy>=1.26.4",
    "pandas>=2.2.0",
    "scikit-learn>=1.5.0",
    "matplotlib>=3.7.0",
    "tqdm>=4.66.4",
    "polars>=1.31.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[dependency-groups]
dev = [
    "ipykernel>=6.30.0",
    "pre-commit>=3.6.0",
]

[tool.uv.workspace]
members = [
    "notebooks/playground-series-s5e9",
    "notebooks/playground",
    "notebooks/cafa",
    ".", "notebooks/nfl-big-data-bowl-2026-prediction",
]
