[project]
name = "stanford"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "kego",
]

[tool.uv.sources]
kego = { path = "../../", editable = true }
